DROP TABLE IF EXISTS Reseptitag CASCADE;
DROP TABLE IF EXISTS Reseptiaine CASCADE;
DROP TABLE IF EXISTS Tag CASCADE;
DROP TABLE IF EXISTS Aine CASCADE;
DROP TABLE IF EXISTS Resepti CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;